# Generated by Django 4.0.6 on 2022-07-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'female'), (2, 'male'), (3, '_')], default=3),
        ),
    ]
